exports.CONNECT = 'connection' // socket连接
exports.DISCONNECT = 'disconnection'
exports.LOGIN = 'LOGIN' // 用户登录
exports.REGISTER = 'REGISTER' // 
exports.LOGOUT = 'LOGOUT' // 用户退出
exports.MESSAGE = 'MESSAGE' // 消息通知
exports.RECEIVEUSERLIST = 'RECEIVEUSERLIST' // 获取用户列表
exports.CREATEROOM = 'CREATEROOM' // 创建群聊房间
exports.VEDIO_OFFER = 'vedio-offer' // 创建RTC视频服务
exports.VEDIO_ANSWER = 'vedio-answer' // 相应RTC视频服务
exports.VEDIO_CANDIDATE = 'vedio-candidate' // 创建RTC-对接层视频服务